// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OLTPSystem.Entities;

public partial class InvoiceLine
{
    public int InvoiceLineId { get; set; }

    public int InvoiceId { get; set; }

    public int PartId { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual Part Part { get; set; }
}